/**
 * Autogenerated by Thrift Compiler (0.17.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.jyami.java.thrift.service;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.17.0)", date = "2023-02-21")
public class RequestWithFlag implements org.apache.thrift.TBase<RequestWithFlag, RequestWithFlag._Fields>, java.io.Serializable, Cloneable, Comparable<RequestWithFlag> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("RequestWithFlag");

  private static final org.apache.thrift.protocol.TField BSON_DATA_FIELD_DESC = new org.apache.thrift.protocol.TField("bsonData", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField FLAG_FIELD_DESC = new org.apache.thrift.protocol.TField("flag", org.apache.thrift.protocol.TType.BOOL, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new RequestWithFlagStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new RequestWithFlagTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.nio.ByteBuffer bsonData; // required
  public boolean flag; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    BSON_DATA((short)1, "bsonData"),
    FLAG((short)2, "flag");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // BSON_DATA
          return BSON_DATA;
        case 2: // FLAG
          return FLAG;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __FLAG_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.BSON_DATA, new org.apache.thrift.meta_data.FieldMetaData("bsonData", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.FLAG, new org.apache.thrift.meta_data.FieldMetaData("flag", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(RequestWithFlag.class, metaDataMap);
  }

  public RequestWithFlag() {
  }

  public RequestWithFlag(
    java.nio.ByteBuffer bsonData,
    boolean flag)
  {
    this();
    this.bsonData = org.apache.thrift.TBaseHelper.copyBinary(bsonData);
    this.flag = flag;
    setFlagIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public RequestWithFlag(RequestWithFlag other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetBsonData()) {
      this.bsonData = org.apache.thrift.TBaseHelper.copyBinary(other.bsonData);
    }
    this.flag = other.flag;
  }

  @Override
  public RequestWithFlag deepCopy() {
    return new RequestWithFlag(this);
  }

  @Override
  public void clear() {
    this.bsonData = null;
    setFlagIsSet(false);
    this.flag = false;
  }

  public byte[] getBsonData() {
    setBsonData(org.apache.thrift.TBaseHelper.rightSize(bsonData));
    return bsonData == null ? null : bsonData.array();
  }

  public java.nio.ByteBuffer bufferForBsonData() {
    return org.apache.thrift.TBaseHelper.copyBinary(bsonData);
  }

  public RequestWithFlag setBsonData(byte[] bsonData) {
    this.bsonData = bsonData == null ? (java.nio.ByteBuffer)null   : java.nio.ByteBuffer.wrap(bsonData.clone());
    return this;
  }

  public RequestWithFlag setBsonData(@org.apache.thrift.annotation.Nullable java.nio.ByteBuffer bsonData) {
    this.bsonData = org.apache.thrift.TBaseHelper.copyBinary(bsonData);
    return this;
  }

  public void unsetBsonData() {
    this.bsonData = null;
  }

  /** Returns true if field bsonData is set (has been assigned a value) and false otherwise */
  public boolean isSetBsonData() {
    return this.bsonData != null;
  }

  public void setBsonDataIsSet(boolean value) {
    if (!value) {
      this.bsonData = null;
    }
  }

  public boolean isFlag() {
    return this.flag;
  }

  public RequestWithFlag setFlag(boolean flag) {
    this.flag = flag;
    setFlagIsSet(true);
    return this;
  }

  public void unsetFlag() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __FLAG_ISSET_ID);
  }

  /** Returns true if field flag is set (has been assigned a value) and false otherwise */
  public boolean isSetFlag() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __FLAG_ISSET_ID);
  }

  public void setFlagIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __FLAG_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case BSON_DATA:
      if (value == null) {
        unsetBsonData();
      } else {
        if (value instanceof byte[]) {
          setBsonData((byte[])value);
        } else {
          setBsonData((java.nio.ByteBuffer)value);
        }
      }
      break;

    case FLAG:
      if (value == null) {
        unsetFlag();
      } else {
        setFlag((java.lang.Boolean)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case BSON_DATA:
      return getBsonData();

    case FLAG:
      return isFlag();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case BSON_DATA:
      return isSetBsonData();
    case FLAG:
      return isSetFlag();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof RequestWithFlag)
      return this.equals((RequestWithFlag)that);
    return false;
  }

  public boolean equals(RequestWithFlag that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_bsonData = true && this.isSetBsonData();
    boolean that_present_bsonData = true && that.isSetBsonData();
    if (this_present_bsonData || that_present_bsonData) {
      if (!(this_present_bsonData && that_present_bsonData))
        return false;
      if (!this.bsonData.equals(that.bsonData))
        return false;
    }

    boolean this_present_flag = true;
    boolean that_present_flag = true;
    if (this_present_flag || that_present_flag) {
      if (!(this_present_flag && that_present_flag))
        return false;
      if (this.flag != that.flag)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetBsonData()) ? 131071 : 524287);
    if (isSetBsonData())
      hashCode = hashCode * 8191 + bsonData.hashCode();

    hashCode = hashCode * 8191 + ((flag) ? 131071 : 524287);

    return hashCode;
  }

  @Override
  public int compareTo(RequestWithFlag other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetBsonData(), other.isSetBsonData());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBsonData()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.bsonData, other.bsonData);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetFlag(), other.isSetFlag());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFlag()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.flag, other.flag);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("RequestWithFlag(");
    boolean first = true;

    sb.append("bsonData:");
    if (this.bsonData == null) {
      sb.append("null");
    } else {
      org.apache.thrift.TBaseHelper.toString(this.bsonData, sb);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("flag:");
    sb.append(this.flag);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (bsonData == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'bsonData' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'flag' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class RequestWithFlagStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public RequestWithFlagStandardScheme getScheme() {
      return new RequestWithFlagStandardScheme();
    }
  }

  private static class RequestWithFlagStandardScheme extends org.apache.thrift.scheme.StandardScheme<RequestWithFlag> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, RequestWithFlag struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // BSON_DATA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.bsonData = iprot.readBinary();
              struct.setBsonDataIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // FLAG
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.flag = iprot.readBool();
              struct.setFlagIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetFlag()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'flag' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, RequestWithFlag struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.bsonData != null) {
        oprot.writeFieldBegin(BSON_DATA_FIELD_DESC);
        oprot.writeBinary(struct.bsonData);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(FLAG_FIELD_DESC);
      oprot.writeBool(struct.flag);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class RequestWithFlagTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public RequestWithFlagTupleScheme getScheme() {
      return new RequestWithFlagTupleScheme();
    }
  }

  private static class RequestWithFlagTupleScheme extends org.apache.thrift.scheme.TupleScheme<RequestWithFlag> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, RequestWithFlag struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeBinary(struct.bsonData);
      oprot.writeBool(struct.flag);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, RequestWithFlag struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.bsonData = iprot.readBinary();
      struct.setBsonDataIsSet(true);
      struct.flag = iprot.readBool();
      struct.setFlagIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

