server:
  shutdown: graceful

redis:
  url: redis://localhost:6379
  stream:
    key: factory-stream
    group: facotry-worker-group
    defaultOffset: 0-0
    groupReadTimeout: 5
    limitPendingTime: 1
  set:
    duplicationKey: duplication_factory_checker
    consumerKey: factory_consumer
  leaderKey: factory_leader

scheduler:
  corePoolSize: 5
  executorTimeout: 20


